# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: messages.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='messages.proto',
  package='InSECTS',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0emessages.proto\x12\x07InSECTS\"\x8c\x01\n\x07Message\x12\x13\n\x0b\x64\x65stination\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x12\n\ndisconnect\x18\x03 \x01(\x08\x12%\n\ttelemetry\x18\x04 \x01(\x0b\x32\x12.InSECTS.Telemetry\x12!\n\x07\x63ommand\x18\x05 \x01(\x0b\x32\x10.InSECTS.Command\"g\n\x07\x43ommand\x12\x30\n\x0fthermal_command\x18\x03 \x01(\x0b\x32\x17.InSECTS.ThermalCommand\x12*\n\x0cset_autonomy\x18\x04 \x01(\x0b\x32\x14.InSECTS.SetAutonomy\"q\n\x0eThermalCommand\x12\x35\n\x12set_servo_position\x18\x01 \x01(\x0b\x32\x19.InSECTS.SetServoPosition\x12(\n\x0b\x66\x61n_control\x18\x02 \x01(\x0b\x32\x13.InSECTS.FanControl\"%\n\x10SetServoPosition\x12\x11\n\tservo_pos\x18\x01 \x01(\x01\"f\n\nFanControl\x12+\n\rset_fan_speed\x18\x01 \x01(\x0b\x32\x14.InSECTS.SetFanSpeed\x12+\n\rset_fan_state\x18\x02 \x01(\x0b\x32\x14.InSECTS.SetFanState\" \n\x0bSetFanSpeed\x12\x11\n\tfan_speed\x18\x01 \x01(\x01\"0\n\x0bSetFanState\x12!\n\tfan_state\x18\x01 \x01(\x0e\x32\x0e.InSECTS.State\"5\n\x0bSetAutonomy\x12&\n\x0e\x61utonomy_state\x18\x01 \x01(\x0e\x32\x0e.InSECTS.State\"A\n\tTelemetry\x12\x34\n\x11thermal_telemetry\x18\x03 \x01(\x0b\x32\x19.InSECTS.ThermalTelemetry\"z\n\x10ThermalTelemetry\x12\x31\n\x0ctemp_reading\x18\x01 \x03(\x0b\x32\x1b.InSECTS.TemperatureReading\x12\x33\n\x11\x66\x61n_speed_reading\x18\x02 \x03(\x0b\x32\x18.InSECTS.FanSpeedReading\"=\n\x12TemperatureReading\x12\x11\n\tsensor_id\x18\x01 \x01(\x05\x12\x14\n\x0csensor_value\x18\x02 \x01(\x01\"4\n\x0f\x46\x61nSpeedReading\x12\x0e\n\x06\x66\x61n_id\x18\x01 \x01(\x05\x12\x11\n\tfan_speed\x18\x02 \x01(\x01*\x18\n\x05State\x12\x07\n\x03OFF\x10\x00\x12\x06\n\x02ON\x10\x01'
)

_STATE = _descriptor.EnumDescriptor(
  name='State',
  full_name='InSECTS.State',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='OFF', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='ON', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=980,
  serialized_end=1004,
)
_sym_db.RegisterEnumDescriptor(_STATE)

State = enum_type_wrapper.EnumTypeWrapper(_STATE)
OFF = 0
ON = 1



_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='InSECTS.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='destination', full_name='InSECTS.Message.destination', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender', full_name='InSECTS.Message.sender', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='disconnect', full_name='InSECTS.Message.disconnect', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='telemetry', full_name='InSECTS.Message.telemetry', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='InSECTS.Message.command', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=28,
  serialized_end=168,
)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='InSECTS.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='thermal_command', full_name='InSECTS.Command.thermal_command', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_autonomy', full_name='InSECTS.Command.set_autonomy', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=170,
  serialized_end=273,
)


_THERMALCOMMAND = _descriptor.Descriptor(
  name='ThermalCommand',
  full_name='InSECTS.ThermalCommand',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='set_servo_position', full_name='InSECTS.ThermalCommand.set_servo_position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fan_control', full_name='InSECTS.ThermalCommand.fan_control', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=275,
  serialized_end=388,
)


_SETSERVOPOSITION = _descriptor.Descriptor(
  name='SetServoPosition',
  full_name='InSECTS.SetServoPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='servo_pos', full_name='InSECTS.SetServoPosition.servo_pos', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=390,
  serialized_end=427,
)


_FANCONTROL = _descriptor.Descriptor(
  name='FanControl',
  full_name='InSECTS.FanControl',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='set_fan_speed', full_name='InSECTS.FanControl.set_fan_speed', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_fan_state', full_name='InSECTS.FanControl.set_fan_state', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=429,
  serialized_end=531,
)


_SETFANSPEED = _descriptor.Descriptor(
  name='SetFanSpeed',
  full_name='InSECTS.SetFanSpeed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fan_speed', full_name='InSECTS.SetFanSpeed.fan_speed', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=533,
  serialized_end=565,
)


_SETFANSTATE = _descriptor.Descriptor(
  name='SetFanState',
  full_name='InSECTS.SetFanState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fan_state', full_name='InSECTS.SetFanState.fan_state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=567,
  serialized_end=615,
)


_SETAUTONOMY = _descriptor.Descriptor(
  name='SetAutonomy',
  full_name='InSECTS.SetAutonomy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='autonomy_state', full_name='InSECTS.SetAutonomy.autonomy_state', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=617,
  serialized_end=670,
)


_TELEMETRY = _descriptor.Descriptor(
  name='Telemetry',
  full_name='InSECTS.Telemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='thermal_telemetry', full_name='InSECTS.Telemetry.thermal_telemetry', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=672,
  serialized_end=737,
)


_THERMALTELEMETRY = _descriptor.Descriptor(
  name='ThermalTelemetry',
  full_name='InSECTS.ThermalTelemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temp_reading', full_name='InSECTS.ThermalTelemetry.temp_reading', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fan_speed_reading', full_name='InSECTS.ThermalTelemetry.fan_speed_reading', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=739,
  serialized_end=861,
)


_TEMPERATUREREADING = _descriptor.Descriptor(
  name='TemperatureReading',
  full_name='InSECTS.TemperatureReading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='InSECTS.TemperatureReading.sensor_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_value', full_name='InSECTS.TemperatureReading.sensor_value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=863,
  serialized_end=924,
)


_FANSPEEDREADING = _descriptor.Descriptor(
  name='FanSpeedReading',
  full_name='InSECTS.FanSpeedReading',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fan_id', full_name='InSECTS.FanSpeedReading.fan_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fan_speed', full_name='InSECTS.FanSpeedReading.fan_speed', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=926,
  serialized_end=978,
)

_MESSAGE.fields_by_name['telemetry'].message_type = _TELEMETRY
_MESSAGE.fields_by_name['command'].message_type = _COMMAND
_COMMAND.fields_by_name['thermal_command'].message_type = _THERMALCOMMAND
_COMMAND.fields_by_name['set_autonomy'].message_type = _SETAUTONOMY
_THERMALCOMMAND.fields_by_name['set_servo_position'].message_type = _SETSERVOPOSITION
_THERMALCOMMAND.fields_by_name['fan_control'].message_type = _FANCONTROL
_FANCONTROL.fields_by_name['set_fan_speed'].message_type = _SETFANSPEED
_FANCONTROL.fields_by_name['set_fan_state'].message_type = _SETFANSTATE
_SETFANSTATE.fields_by_name['fan_state'].enum_type = _STATE
_SETAUTONOMY.fields_by_name['autonomy_state'].enum_type = _STATE
_TELEMETRY.fields_by_name['thermal_telemetry'].message_type = _THERMALTELEMETRY
_THERMALTELEMETRY.fields_by_name['temp_reading'].message_type = _TEMPERATUREREADING
_THERMALTELEMETRY.fields_by_name['fan_speed_reading'].message_type = _FANSPEEDREADING
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['ThermalCommand'] = _THERMALCOMMAND
DESCRIPTOR.message_types_by_name['SetServoPosition'] = _SETSERVOPOSITION
DESCRIPTOR.message_types_by_name['FanControl'] = _FANCONTROL
DESCRIPTOR.message_types_by_name['SetFanSpeed'] = _SETFANSPEED
DESCRIPTOR.message_types_by_name['SetFanState'] = _SETFANSTATE
DESCRIPTOR.message_types_by_name['SetAutonomy'] = _SETAUTONOMY
DESCRIPTOR.message_types_by_name['Telemetry'] = _TELEMETRY
DESCRIPTOR.message_types_by_name['ThermalTelemetry'] = _THERMALTELEMETRY
DESCRIPTOR.message_types_by_name['TemperatureReading'] = _TEMPERATUREREADING
DESCRIPTOR.message_types_by_name['FanSpeedReading'] = _FANSPEEDREADING
DESCRIPTOR.enum_types_by_name['State'] = _STATE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.Message)
  })
_sym_db.RegisterMessage(Message)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.Command)
  })
_sym_db.RegisterMessage(Command)

ThermalCommand = _reflection.GeneratedProtocolMessageType('ThermalCommand', (_message.Message,), {
  'DESCRIPTOR' : _THERMALCOMMAND,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.ThermalCommand)
  })
_sym_db.RegisterMessage(ThermalCommand)

SetServoPosition = _reflection.GeneratedProtocolMessageType('SetServoPosition', (_message.Message,), {
  'DESCRIPTOR' : _SETSERVOPOSITION,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.SetServoPosition)
  })
_sym_db.RegisterMessage(SetServoPosition)

FanControl = _reflection.GeneratedProtocolMessageType('FanControl', (_message.Message,), {
  'DESCRIPTOR' : _FANCONTROL,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.FanControl)
  })
_sym_db.RegisterMessage(FanControl)

SetFanSpeed = _reflection.GeneratedProtocolMessageType('SetFanSpeed', (_message.Message,), {
  'DESCRIPTOR' : _SETFANSPEED,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.SetFanSpeed)
  })
_sym_db.RegisterMessage(SetFanSpeed)

SetFanState = _reflection.GeneratedProtocolMessageType('SetFanState', (_message.Message,), {
  'DESCRIPTOR' : _SETFANSTATE,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.SetFanState)
  })
_sym_db.RegisterMessage(SetFanState)

SetAutonomy = _reflection.GeneratedProtocolMessageType('SetAutonomy', (_message.Message,), {
  'DESCRIPTOR' : _SETAUTONOMY,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.SetAutonomy)
  })
_sym_db.RegisterMessage(SetAutonomy)

Telemetry = _reflection.GeneratedProtocolMessageType('Telemetry', (_message.Message,), {
  'DESCRIPTOR' : _TELEMETRY,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.Telemetry)
  })
_sym_db.RegisterMessage(Telemetry)

ThermalTelemetry = _reflection.GeneratedProtocolMessageType('ThermalTelemetry', (_message.Message,), {
  'DESCRIPTOR' : _THERMALTELEMETRY,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.ThermalTelemetry)
  })
_sym_db.RegisterMessage(ThermalTelemetry)

TemperatureReading = _reflection.GeneratedProtocolMessageType('TemperatureReading', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATUREREADING,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.TemperatureReading)
  })
_sym_db.RegisterMessage(TemperatureReading)

FanSpeedReading = _reflection.GeneratedProtocolMessageType('FanSpeedReading', (_message.Message,), {
  'DESCRIPTOR' : _FANSPEEDREADING,
  '__module__' : 'messages_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.FanSpeedReading)
  })
_sym_db.RegisterMessage(FanSpeedReading)


# @@protoc_insertion_point(module_scope)
