---
  version: "v0.1"
  virtual_machine: false  # Is the system running in a vm?
  emulate_sdr: true       # Should the SDR be emulated (i.e. SDR not present)
  emulate_arduino: false  # Should the arduino be emulated (i.e. arduino not present)
  emulate_thermal: false  # Should the thermal system be emulated
  telemetry_freq: 1.0     # Hz

  command_multicast_ip: "224.1.1.30"
  command_multicast_port: 5051
  telemetry_multicast_ip: "224.1.1.40"
  telemetry_multicast_port: 5061

  # ---- sdr_app ----
  sdr_tcp_server_ip: "127.0.0.1"
  sdr_tcp_server_port: 5000

  # ---- hal_service ----
  arduino_address: "/dev/ttyACM0"
  serial_baudrate: 115200

