# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import config_pb2 as config__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='message.proto',
  package='InSECTS',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rmessage.proto\x12\x07InSECTS\x1a\x0c\x63onfig.proto\"\xc7\x01\n\x07Message\x12\x13\n\x0b\x64\x65stination\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0b\n\x03\x61\x63k\x18\x03 \x01(\x08\x12\x12\n\ndisconnect\x18\x04 \x01(\x08\x12!\n\x07\x63ommand\x18\x05 \x01(\x0b\x32\x10.InSECTS.Command\x12%\n\ttelemetry\x18\x06 \x01(\x0b\x32\x12.InSECTS.Telemetry\x12,\n\rconfig_params\x18\x07 \x01(\x0b\x32\x15.InSECTS.ConfigParams\"\xd1\x01\n\x07\x43ommand\x12\x35\n\x12set_servo_position\x18\x01 \x01(\x0b\x32\x19.InSECTS.SetServoPosition\x12+\n\rset_fan_speed\x18\x02 \x01(\x0b\x32\x14.InSECTS.SetFanSpeed\x12+\n\rset_fan_state\x18\x03 \x01(\x0b\x32\x14.InSECTS.SetFanState\x12\x35\n\x12set_autonomy_state\x18\x04 \x01(\x0b\x32\x19.InSECTS.SetAutonomyState\"%\n\x10SetServoPosition\x12\x11\n\tservo_pos\x18\x01 \x01(\x01\" \n\x0bSetFanSpeed\x12\x11\n\tfan_speed\x18\x01 \x01(\x01\" \n\x0bSetFanState\x12\x11\n\tfan_state\x18\x01 \x01(\x08\"*\n\x10SetAutonomyState\x12\x16\n\x0e\x61utonomy_state\x18\x01 \x01(\x08\"q\n\tTelemetry\x12\x32\n\x10temperature_data\x18\x01 \x01(\x0b\x32\x18.InSECTS.TemperatureData\x12\x30\n\x11\x66\x61n_speed_reading\x18\x02 \x01(\x0b\x32\x15.InSECTS.FanSpeedData\":\n\x0fTemperatureData\x12\x11\n\tsensor_id\x18\x01 \x01(\x05\x12\x14\n\x0csensor_value\x18\x02 \x01(\x01\"1\n\x0c\x46\x61nSpeedData\x12\x0e\n\x06\x66\x61n_id\x18\x01 \x01(\x05\x12\x11\n\tfan_speed\x18\x02 \x01(\x01'
  ,
  dependencies=[config__pb2.DESCRIPTOR,])




_MESSAGE = _descriptor.Descriptor(
  name='Message',
  full_name='InSECTS.Message',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='destination', full_name='InSECTS.Message.destination', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sender', full_name='InSECTS.Message.sender', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ack', full_name='InSECTS.Message.ack', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='disconnect', full_name='InSECTS.Message.disconnect', index=3,
      number=4, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='InSECTS.Message.command', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='telemetry', full_name='InSECTS.Message.telemetry', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='config_params', full_name='InSECTS.Message.config_params', index=6,
      number=7, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=41,
  serialized_end=240,
)


_COMMAND = _descriptor.Descriptor(
  name='Command',
  full_name='InSECTS.Command',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='set_servo_position', full_name='InSECTS.Command.set_servo_position', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_fan_speed', full_name='InSECTS.Command.set_fan_speed', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_fan_state', full_name='InSECTS.Command.set_fan_state', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='set_autonomy_state', full_name='InSECTS.Command.set_autonomy_state', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=243,
  serialized_end=452,
)


_SETSERVOPOSITION = _descriptor.Descriptor(
  name='SetServoPosition',
  full_name='InSECTS.SetServoPosition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='servo_pos', full_name='InSECTS.SetServoPosition.servo_pos', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=454,
  serialized_end=491,
)


_SETFANSPEED = _descriptor.Descriptor(
  name='SetFanSpeed',
  full_name='InSECTS.SetFanSpeed',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fan_speed', full_name='InSECTS.SetFanSpeed.fan_speed', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=493,
  serialized_end=525,
)


_SETFANSTATE = _descriptor.Descriptor(
  name='SetFanState',
  full_name='InSECTS.SetFanState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fan_state', full_name='InSECTS.SetFanState.fan_state', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=527,
  serialized_end=559,
)


_SETAUTONOMYSTATE = _descriptor.Descriptor(
  name='SetAutonomyState',
  full_name='InSECTS.SetAutonomyState',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='autonomy_state', full_name='InSECTS.SetAutonomyState.autonomy_state', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=561,
  serialized_end=603,
)


_TELEMETRY = _descriptor.Descriptor(
  name='Telemetry',
  full_name='InSECTS.Telemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='temperature_data', full_name='InSECTS.Telemetry.temperature_data', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fan_speed_reading', full_name='InSECTS.Telemetry.fan_speed_reading', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=605,
  serialized_end=718,
)


_TEMPERATUREDATA = _descriptor.Descriptor(
  name='TemperatureData',
  full_name='InSECTS.TemperatureData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='sensor_id', full_name='InSECTS.TemperatureData.sensor_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='sensor_value', full_name='InSECTS.TemperatureData.sensor_value', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=720,
  serialized_end=778,
)


_FANSPEEDDATA = _descriptor.Descriptor(
  name='FanSpeedData',
  full_name='InSECTS.FanSpeedData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='fan_id', full_name='InSECTS.FanSpeedData.fan_id', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fan_speed', full_name='InSECTS.FanSpeedData.fan_speed', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=780,
  serialized_end=829,
)

_MESSAGE.fields_by_name['command'].message_type = _COMMAND
_MESSAGE.fields_by_name['telemetry'].message_type = _TELEMETRY
_MESSAGE.fields_by_name['config_params'].message_type = config__pb2._CONFIGPARAMS
_COMMAND.fields_by_name['set_servo_position'].message_type = _SETSERVOPOSITION
_COMMAND.fields_by_name['set_fan_speed'].message_type = _SETFANSPEED
_COMMAND.fields_by_name['set_fan_state'].message_type = _SETFANSTATE
_COMMAND.fields_by_name['set_autonomy_state'].message_type = _SETAUTONOMYSTATE
_TELEMETRY.fields_by_name['temperature_data'].message_type = _TEMPERATUREDATA
_TELEMETRY.fields_by_name['fan_speed_reading'].message_type = _FANSPEEDDATA
DESCRIPTOR.message_types_by_name['Message'] = _MESSAGE
DESCRIPTOR.message_types_by_name['Command'] = _COMMAND
DESCRIPTOR.message_types_by_name['SetServoPosition'] = _SETSERVOPOSITION
DESCRIPTOR.message_types_by_name['SetFanSpeed'] = _SETFANSPEED
DESCRIPTOR.message_types_by_name['SetFanState'] = _SETFANSTATE
DESCRIPTOR.message_types_by_name['SetAutonomyState'] = _SETAUTONOMYSTATE
DESCRIPTOR.message_types_by_name['Telemetry'] = _TELEMETRY
DESCRIPTOR.message_types_by_name['TemperatureData'] = _TEMPERATUREDATA
DESCRIPTOR.message_types_by_name['FanSpeedData'] = _FANSPEEDDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Message = _reflection.GeneratedProtocolMessageType('Message', (_message.Message,), {
  'DESCRIPTOR' : _MESSAGE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.Message)
  })
_sym_db.RegisterMessage(Message)

Command = _reflection.GeneratedProtocolMessageType('Command', (_message.Message,), {
  'DESCRIPTOR' : _COMMAND,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.Command)
  })
_sym_db.RegisterMessage(Command)

SetServoPosition = _reflection.GeneratedProtocolMessageType('SetServoPosition', (_message.Message,), {
  'DESCRIPTOR' : _SETSERVOPOSITION,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.SetServoPosition)
  })
_sym_db.RegisterMessage(SetServoPosition)

SetFanSpeed = _reflection.GeneratedProtocolMessageType('SetFanSpeed', (_message.Message,), {
  'DESCRIPTOR' : _SETFANSPEED,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.SetFanSpeed)
  })
_sym_db.RegisterMessage(SetFanSpeed)

SetFanState = _reflection.GeneratedProtocolMessageType('SetFanState', (_message.Message,), {
  'DESCRIPTOR' : _SETFANSTATE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.SetFanState)
  })
_sym_db.RegisterMessage(SetFanState)

SetAutonomyState = _reflection.GeneratedProtocolMessageType('SetAutonomyState', (_message.Message,), {
  'DESCRIPTOR' : _SETAUTONOMYSTATE,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.SetAutonomyState)
  })
_sym_db.RegisterMessage(SetAutonomyState)

Telemetry = _reflection.GeneratedProtocolMessageType('Telemetry', (_message.Message,), {
  'DESCRIPTOR' : _TELEMETRY,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.Telemetry)
  })
_sym_db.RegisterMessage(Telemetry)

TemperatureData = _reflection.GeneratedProtocolMessageType('TemperatureData', (_message.Message,), {
  'DESCRIPTOR' : _TEMPERATUREDATA,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.TemperatureData)
  })
_sym_db.RegisterMessage(TemperatureData)

FanSpeedData = _reflection.GeneratedProtocolMessageType('FanSpeedData', (_message.Message,), {
  'DESCRIPTOR' : _FANSPEEDDATA,
  '__module__' : 'message_pb2'
  # @@protoc_insertion_point(class_scope:InSECTS.FanSpeedData)
  })
_sym_db.RegisterMessage(FanSpeedData)


# @@protoc_insertion_point(module_scope)
